### ISSUE TITLE
Walletd or TurtleCoind is already running... using remote node

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtle-wallet-go#10]
Heya,

If I go to open a wallet, using a remote node, it will report this. Upon re-entering my password and re-opening it will work fine the second time. I seem to be able to reproduce this every time. On linux.

**Comment by woodyjon** [comment]
Isn't it because you open a wallet less than 4-5 sec after closing one? That is the only way I can reproduce.
Walletd takes a few seconds to close after closing a wallet, so might it be the issue you are experiencing?

**Comment by ZedPea** [comment]
Yep, you are correct of course. For some reason I was thinking walletd wouldn't need to be running when you were using a remote node!
