### ISSUE TITLE
Coin send 

### ISSUE THREAD

**Issue by Jihadist** [turtlecoin/turtle-wallet-go#13]
I tried send 10001 coins to tradeogre and catched error
![image](https://user-images.githubusercontent.com/26579016/40353754-eb408132-5dba-11e8-91e8-7cddf046c5de.png)
Walletd has this string in log
> 2018-May-22 12:15:50.115146 INFO    transfer, from {}, to {<10001.00, TRTLv1Hqo3wHdqLRXuCyX3MwvzKyxzwXeBtycnkDy8ceFp4E23bm3P467xLEbUusH6Q1mqQUBiYwJ2yULJbvr5nKe8kcyc4uyps>}, change address '', fee 0.10, mixin 5, unlockTimestamp 0

and coinnest log has this transaction

**Comment by ZedPea** [comment]
I'm not seeing what the error is here, it looks like the transfer went fine?

**Comment by Jihadist** [comment]
Nope, the application hadnt been responding for ~30 minutes then i closed it but transaction hasnt completed yet. I dont see any errors in logs but it was

**Comment by woodyjon** [comment]
I believe it must be linked to that https://github.com/turtlecoin/turtlecoin/issues/286
We are trying to understand the problem and find a solution.

**Comment by woodyjon** [comment]
I think this is fixed in latest release. Please re-open if you still encounter that issue after upgrading.
