### ISSUE TITLE
show version in the UI

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtle-wallet-go#14]
from discord user `andready#9246`

![screenshot_20180526-171150 01](https://user-images.githubusercontent.com/317/40575373-2027d23c-610e-11e8-9743-dc9b639820c1.png)

**Comment by woodyjon** [comment]
Ok, on it!
For info, the version is already displayed in the logs.
For the "update available", it is more complicated, and I am not a fan of it. That would mean continuously requesting one of my server, meaning that I could theoretically log info on people, and I don't want to do that or give that impression. What do you think? Or maybe there is another way..
Requesting github might be possible, but if I upload a beta release, I don't want to have people think there is an update to be downloaded.

**Comment by ZedPea** [comment]
I believe you can mark github releases as pre-release - probably you can check this via the api as well, so you only notify on stable releases?

**Comment by woodyjon** [comment]
Yes indeed, should be possible. I'll check that. Thanks.

**Comment by woodyjon** [comment]
Version number is now displayed (from version 0.23). Open the info screen by clicking the question mark on the top right.

**Comment by woodyjon** [comment]
I implemented the display of next version if available 8540c3985082dad79eb7219a263cfc6c27c855d0.
So will be included in next release.
