### ISSUE TITLE
Very tiny text on HiDPI screen

### ISSUE THREAD

**Issue by Noiden** [turtlecoin/turtle-wallet-go#15]
I got a 4K Screen and the text is very tiny.

![image](https://user-images.githubusercontent.com/4354201/41058898-4f47e672-69cb-11e8-9f35-d211b8101575.png)

**Comment by woodyjon** [comment]
On which OS are you?

**Comment by Noiden** [comment]
@woodyjon Windows 10 Pro.

**Comment by woodyjon** [comment]
I am sorry, but it is very difficult for me to debug this at the moment as I don't have a 4K screen.
They have info about this [here](http://doc.qt.io/qt-5/highdpi.html), but I will not be able to implement right now.

**Comment by CaptainGinyu** [comment]
@Noiden Not sure if you're still having this issue, but essentially, here's what you do (this works not only for this wallet, but for many other apps on 4k screens that appear "too small"):

1. First go to the folder where the Nest wallet is located.
2. Open up Notepad and paste the following:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.Windows.Common-Controls"
      version="6.0.0.0" processorArchitecture="*"
      publicKeyToken="6595b64144ccf1df"
      language="*">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.VC90.CRT"
      version="9.0.21022.8"
      processorArchitecture="amd64"
      publicKeyToken="1fc8b3b9a1e18e3b">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
  <security>
    <requestedPrivileges>
      <requestedExecutionLevel
        level="asInvoker"
        uiAccess="false"/>
    </requestedPrivileges>
  </security>
</trustInfo>

<asmv3:application>
  <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</ms_windowsSettings:dpiAware>
  </asmv3:windowsSettings>
</asmv3:application>

</assembly>
```
3. After pasting the code from above, save the file as `TurtleCoin-Nest.exe.manifest`.  Make sure the name is **exactly** that.  This file should go in the same folder as your wallet.
4. Open up regedit by going to your Windows Start menu, typing in regedit and pressing Enter.
5. Navigate to **HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Windows > CurrentVersion > SideBySide**.
6. Right-click on the right pane, select **NEW > DWORD (32 bit) Value**.
7. Type PreferExternalManifest, and then press ENTER.
8. Right-click PreferExternalManifest, and then click Modify.
9. Enter 1 in Value Data.  (You can have either Decimal or Hexidecimal... it doesn't matter which)
10. Press Ok and exit out of the registry editor.
11. Try opening up your wallet again.  Hopefully the scaling issue will be solved.

Source: https://www.danantonielli.com/adobe-app-scaling-on-high-dpi-displays-fix/

**Comment by woodyjon** [comment]
I implemented a fix. It will be included in the next release.

**Comment by woodyjon** [comment]
released
