### ISSUE TITLE
Error opening wallet

### ISSUE THREAD

**Issue by Jihadist** [turtlecoin/turtle-wallet-go#16]
I catch this error on windows and ubuntu

> user@pc:/media/user/Files/TurtleCoin-Nest-0.22$ ./TurtleCoin-Nest.sh
> time="2018-06-09T12:48:40+03:00" level=info msg="Application started" version=0.22
> qrc:/qml/nestmain.qml:72:5: QML Connections: Cannot assign to non-existent property "onHideSettingsScreen"
> qrc:/qml/nestmain.qml:72:5: QML Connections: Cannot assign to non-existent property "onDisplaySettingsScreen"
> qrc:/qml/nestmain.qml:72:5: QML Connections: Cannot assign to non-existent property "onDisplayMainWalletScreen"
> qrc:/qml/nestmain.qml:72:5: QML Connections: Cannot assign to non-existent property "onDisplayOpenWalletScreen"
> qrc:/qml/nestmain.qml:72:5: QML Connections: Cannot assign to non-existent property "onDisplayErrorDialog"
> qrc:/qml/Settings.qml:295:5: QML Connections: Cannot assign to non-existent property "onDisplaySettingsRemoteDaemonInfo"
> qrc:/qml/Settings.qml:295:5: QML Connections: Cannot assign to non-existent property "onDisplaySettingsValues"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplayDefaultFeeAndMixin"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplayFullBalanceInTransferAmount"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplayAddress"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplayTotalBalance"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplaySyncingInfo"
> qrc:/qml/Wallet.qml:1381:5: QML Connections: Cannot assign to non-existent property "onDisplayPrivateKeys"
> qrc:/qml/Wallet.qml:1084:9: QML Connections: Cannot assign to non-existent property "onDisplayPopup"
> qrc:/qml/Wallet.qml:653:17: QML Connections: Cannot assign to non-existent property "onClearTransferAmount"
> qrc:/qml/Wallet.qml:515:9: QML Connections: Cannot assign to non-existent property "onClearListTransactions"
> qrc:/qml/Wallet.qml:444:17: QML Connections: Cannot assign to non-existent property "onUpdateConfirmationsOfTransaction"
> qrc:/qml/Wallet.qml:444:17: QML Connections: Cannot assign to non-existent property "onAddTransactionToList"
> qrc:/qml/Wallet.qml:126:17: QML Connections: Cannot assign to non-existent property "onDisplayAvailableBalance"
> qrc:/qml/Wallet.qml:105:17: QML Connections: Cannot assign to non-existent property "onDisplayLockedBalance"
> qrc:/qml/OpenWallet.qml:889:5: QML Connections: Cannot assign to non-existent property "onDisplayUseRemoteNode"
> qrc:/qml/OpenWallet.qml:889:5: QML Connections: Cannot assign to non-existent property "onDisplayWalletCreationLocation"
> qrc:/qml/OpenWallet.qml:889:5: QML Connections: Cannot assign to non-existent property "onDisplayPathToPreviousWallet"
> qrc:/qml/OpenWallet.qml:889:5: QML Connections: Cannot assign to non-existent property "onFinishedCreatingWallet"
> qrc:/qml/OpenWallet.qml:889:5: QML Connections: Cannot assign to non-existent property "onFinishedLoadingWalletd"
> qrc:/qml/OpenWallet.qml:890: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:106: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:127: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:445: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:516: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:654: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:1085: ReferenceError: QmlBridge is not defined
> qrc:/qml/Wallet.qml:1382: ReferenceError: QmlBridge is not defined
> qrc:/qml/Settings.qml:296: ReferenceError: QmlBridge is not defined
> qrc:/qml/nestmain.qml:73: ReferenceError: QmlBridge is not defined
> Gtk-Message: 12:48:44.922: GtkDialog mapped without a transient parent. This is discouraged.
> time="2018-06-09T12:49:15+03:00" level=info msg="Walletd killed as stopping process timed out"
> time="2018-06-09T12:49:15+03:00" level=warning msg="error starting walletd with provided wallet info. error: error communicating with walletd via rpc"

Simple wallet works but this doesn't. No vpn no proxy

**Comment by Sayyiditow** [comment]
This issue is annoying, the CLI wallet itself is not working, sending funds gives an error, this is also not working. Annoying af!

**Comment by woodyjon** [comment]
I think this is fixed in latest release (0.23). Please re-open if you still encounter that issue after upgrading.

**Comment by Jihadist** [comment]
![023](https://user-images.githubusercontent.com/26579016/41840827-6811d764-786f-11e8-9c4b-48bda2dd3902.jpg)
Error wasnt fixed in 0.23

**Comment by woodyjon** [comment]
Can you give me the content of walletdCurrentSession.log ?

**Comment by woodyjon** [comment]
Did you extract/uncompress the folder before launching nest?

**Comment by woodyjon** [comment]
Ok. Strange but all good now.

**Comment by Jihadist** [comment]
If i catch this error again i will give you log
