### ISSUE TITLE
TurtleCoin-Nest.sh file doesn't work correctly in a folder with spaces

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-go#17]
I have not confirmed this, but a user was getting the error:

```
TurtleCoin-Nest.sh: 10: export: /TurtleCoin-Nest-0.22/./lib: bad variable name
```

When they moved the download to a folder without spaces, it then worked.

**Comment by woodyjon** [comment]
There are all kinds of problems with directories with spaces, not even necessarily linked to nest's script. Isn't it ok to just tell the people who encounter that to remove the spaces?

**Comment by ZedPea** [comment]
Up to you of course, but it's not the most user friendly. It should at the very least try and display some sort of error, whilst most users will know to run a .sh script from the CLI to get better output, others might just double click it, and "nothing happens".

Would not just quoting your variables make the script work?

**Comment by LithyRiolu** [comment]
I'm going to close this because `TurtleCoin-Nest.sh` no longer exists. There is a new build script which IBMCD wrote for Linux which doesn't seem to have any problems https://github.com/turtlecoin/turtle-wallet-go/blob/dev/build-linux.sh
