### ISSUE TITLE
[ENHANCEMENT] Auto save wallet file periodically or upon sync done

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtle-wallet-go#18]
If users shut down windows, force close the program, or whatever, it appears that the wallet sync progress will be lost.

Perhaps the wallet should be auto saved every so often, or saved upon successfully syncing.

**Comment by woodyjon** [comment]
Yes indeed, I also thought about implementing that. It's coming then.

**Comment by woodyjon** [comment]
b8a28f5a042c08f26fbf67db469bd6c8c1847421
