### ISSUE TITLE
Make PAYMENT ID / Transaction ID Mandatory

### ISSUE THREAD

**Issue by gnatsstang23** [turtlecoin/turtle-wallet-go#19]
Take out the 'OPTIONAL'  Tag on PAYMENT ID in wallet. INSTEAD, Use a drop-down Squib, to say that 'SOME transactions may require A TRANSACTION ID to be completed. I lost 140 TRTL sending it to my tip jar...not knowing that I would HAVE to have the Trans ID. 
Most users are not going to RTFM. Not going to happen. I don't want bad publicity due to the fact that a user lost X TRTL. because they made a simple mistake like forgetting the Trans ID.
Simple Fix Simple Solution.
Thank You.

**Comment by woodyjon** [comment]
OK good point. I'll leave the "(optional)", but add a line below like "warning: if you were asked by your recipient to include a payment ID, you must include it here".

**Comment by woodyjon** [comment]
35d432193f8da2711b79a53fbb7be3278541557e
