### ISSUE TITLE
Recalculating The BLOCKCHAIN

### ISSUE THREAD

**Issue by gnatsstang23** [turtlecoin/turtle-wallet-go#20]
Can you make something that saves the state of the blockchain... so that when a user logs off, They dont have to recalculate the whole thing on startup?
A save State would be a great thing to have...
Imagine coming back in 6 months and having to Download 1 Billion Transactions? Not a good thing.
Some way to save current state would be a great thing.
Thank you!

**Comment by woodyjon** [comment]
State of the wallet is normally saved. It is not saved, however, when walletd crashes. This will be fixed. See here: https://github.com/turtlecoin/turtle-wallet-go/issues/18

**Comment by woodyjon** [comment]
b8a28f5a042c08f26fbf67db469bd6c8c1847421
