### ISSUE TITLE
OSX: render font in higher rest for retina screens (High DPI Displays)

### ISSUE THREAD

**Issue by gianpaj** [turtlecoin/turtle-wallet-go#22]
There should be a setting for QT.

http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/
http://doc.qt.io/qt-5/highdpi.html

![turtlecoin_nest_and_google](https://user-images.githubusercontent.com/899175/41488545-571ec308-70f5-11e8-884c-6a02be1fafb5.png)

**Comment by woodyjon** [comment]
fixed in ff35fd4d853009685bd112e930316783ba3bbaf2
Thank you for the links!

**Comment by gianpaj** [comment]
Great stuff! looking forward to trying it out.
