### ISSUE TITLE
Remove artificial 5MM cap on transactions

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtle-wallet-go#23]
So there's a 5 million turtle limit when sending transactions, to try and avoid making transactions that will get stuck in the transaction pool.

However the walletd code has already been modified to reject any transactions that will possibly get stuck in the transaction pool, so this limit only really holds back users who have a quite optimized wallet.

Thanks!

**Comment by woodyjon** [comment]
👍

**Comment by woodyjon** [comment]
Removed for next release. 45829f10fdd9f78edf99766be6de8827ae57f080
