### ISSUE TITLE
[Enhancement] Saved wallet address' for future use of one click

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtle-wallet-go#24]
This enhancement would make common wallet or payment ID transfers easier.

Example: 
Wallet to Exchange - ID and payment ID never change. Insert save button on GUI and saves wallet address' to a address_list.txt file that can be called for address list upon opening wallet file on GUI.

**Comment by woodyjon** [comment]
Thanks for the proposal. Ok I will implement that if it does not make my UI too crowded. It will not be before a few weeks, though.

**Comment by BigslimVdub** [comment]
any update?

**Comment by zpalmtree** [comment]
I think this got implemented if I remember the commit history

**Comment by BigslimVdub** [comment]
ahh duh, I guess I never bothered to check since I wrote this. It's there. Closing. 
![turtle saved address](https://user-images.githubusercontent.com/30030687/45663436-0e407480-bacc-11e8-9c4a-e98e6069eec7.png)
