### ISSUE TITLE
Invalid mnemonic seed will not display a helpful error to user

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtle-wallet-go#27]
Maybe this was fixed when we fixed up it not logging correctly, but I recently saw someone entering an invalid seed, and they got an error "walletd stopped with unknown error".
Had to dig into walletd.log to see what was occurring.

**Comment by woodyjon** [comment]
Yes, as soon as walletd will be updated, the specific error will be displayed.

**Comment by ZedPea** [comment]
Nice :+1:
