### ISSUE TITLE
Walletd not working on Linux - (SIGILL)

### ISSUE THREAD

**Issue by ms502040** [turtlecoin/turtle-wallet-go#28]
While running Walletd even when creating new wallet or opening existing one or ./walletd from console i got this error (SIGILL):
~~~
time="2018-08-01T07:37:42+02:00" level=warning msg="Walletd finished with error: signal: illegal instruction (core dumped)"
time="2018-08-01T07:37:42+02:00" level=info msg="Walletd killed without error"
time="2018-08-01T07:37:42+02:00" level=warning msg="error starting walletd with provided wallet info. error: error communicating with walletd via rpc"
~~~
OS: openSuse 42.3
CPU: AMD Opteron 6272
wallet:  TurtleCoin-Nest-0.30-Linux

**Comment by woodyjon** [comment]
That is an architecture issue, you must compile walletd yourself on your computer and it should work. Follow the compiling instructions on the following link and once done, copy the walletd which is in turtlecoin/build/src to the Nest folder.

https://github.com/turtlecoin/turtlecoin/releases/tag/v0.6.3

**Comment by ms502040** [comment]
I understand that is architecture issue and I must recompile wallet, but for lamer user very hard to determine this issue and maybe recompile too. Maybe better compile release wallet architecture independent or or two releases for AMD, x64 arch?

**Comment by woodyjon** [comment]
I understand, but for most users, the compiled builds work. It is impossible to compile for every architectures. If you can build for an architecture that you think would help several users, please share your build and it could be added to the turtlecoin release page.
