### ISSUE TITLE
Wrong wallet version?

### ISSUE THREAD

**Issue by randygrolemund** [turtlecoin/turtle-wallet-go#29]
All of a sudden I cannot send..... network errors. Restarted the wallet, and now I get wrong wallet version. I've been running .3 since it came out, and the wallet was generated with this version. Wallet accepted coin this morning, and is dated today.

It's now giving this error:

![image](https://user-images.githubusercontent.com/8581255/43581155-95fec1b6-961d-11e8-8a10-59d4fd9a887b.png)

Ideas?

**Comment by randygrolemund** [comment]
I recreated the wallet file, and it's now working again. I've done this 2x with this version.

Plans to add an address book?

**Comment by woodyjon** [comment]
"wrong version" is usually when it is not a wallet file which is being opened (sometimes people try to open walletd instead of their wallet file). Make sure you try to open your wallet file (usually a .wallet).

**Comment by woodyjon** [comment]
Yes, I'll add an address book at some point.

**Comment by randygrolemund** [comment]
Thanks for the reply.... yes opening the actual wallet file :)
