### ISSUE TITLE
tryin to build from source...

### ISSUE THREAD

**Issue by xaria-coin** [turtlecoin/turtle-wallet-go#31]
but keep getting this error...

moc.cpp:9:10: fatal error: QByteArray: No such file or directory
 #include <QByteArray>
          ^~~~~~~~~~~~
compilation terminated.

**Comment by woodyjon** [comment]
You installed QT 5.10.1, followed all the installation steps here https://github.com/therecipe/qt/wiki/Installation , and ran `$ qtdeploy build desktop`?
What command did you use for building?

**Comment by xaria-coin** [comment]
That's the error I get on running qtdeploy build desktop

**Comment by woodyjon** [comment]
I'm sorry but I think that this is something linked to therecipe qt bindings. I don't know all the details on how it works. You should open an issue there and the guy will help you. Did all the examples work when you did qtsetup?

**Comment by woodyjon** [comment]
No, but to install their bindings, at some point you have to run a script called "qtsetup". And at the end of that script, it will automatically launch several examples of applications. If they run well, you know that everything is installed correctly.

**Comment by xaria-coin** [comment]
Ah yes, that popped up, there were numerous gui things like a calculator and some other bits

**Comment by woodyjon** [comment]
Then your install must be fine. Sorry I don't know what is the issue there. Can you confirm that you installed QT 5.10.1 and that you set the environmental variable QT_VERSION=5.10.1 ?

**Comment by woodyjon** [comment]
Can you run `$ qtsetup check` and paste the result?

**Comment by xaria-coin** [comment]
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10.1'      
INFO[0000] GOROOT:                      '/usr/lib/go-1.10' 
INFO[0000] GOPATH:                      '/home/andy/go' 
INFO[0000] GOBIN:                       '/home/andy/go/bin' 
INFO[0000] QT_HASH:                     'ad4b26dcd5d05cbd3e39c874b80b79213244f845' 
INFO[0000] QT_VERSION:                  '5.11.1'        
INFO[0000] QT_VERSION_MAJOR:            '5.11.1'        
INFO[0000] QT_DIR:                      '/home/andy/Qt5.11.1' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:               'false'


ive somehow managed to get past that now and compiled but the gui doesnt load

**Comment by woodyjon** [comment]
OK, cool that the compilation succeeded. The only difference with me is that you're on QT 5.11.1, I'm on 5.10.1.
You should try with 5.10.1, there will be less chance of issues.
Otherwise, when you launch the gui with ./TurtleCoin-Nest.sh in the terminal, usually you will see the errors if it does not launch. But if you did not change anything and use 5.10.1, it should work.
I would also advicse to try my version first and than make your modifications one step at a time.

**Comment by jerme404** [comment]
@xaria-coin did you find a solution for this?  I'm having the same problem.

**Comment by hmc36093** [comment]
I followed all the instructions to make a new coin but it hangs on the make process at about 70%. 
also- do i leave the 2nd block with all our numbers or do i make it 0 ? or what ?

-- it hangs here. 
[ 69%] Building CXX object src/CMakeFiles/Rpc.dir/Rpc/HttpClient.cpp.o
[ 70%] Building CXX object src/CMakeFiles/Rpc.dir/Rpc/HttpServer.cpp.o
[ 70%] Building CXX object src/CMakeFiles/Rpc.dir/Rpc/JsonRpc.cpp.o
[ 70%] Building CXX object src/CMakeFiles/Rpc.dir/Rpc/RpcServer.cpp.o
In file included from /root/AmericanEagleDollar/src/CryptoNoteCore/BlockchainCache.h:33,
                 from /root/AmericanEagleDollar/src/CryptoNoteCore/Core.h:10,
                 from /root/AmericanEagleDollar/src/Rpc/RpcServer.cpp:15:
/root/AmericanEagleDollar/src/CryptoNoteCore/Currency.h: In member function ‘uint64_t CryptoNote::Currency::defaultDustThreshold(uint32_t) const’:
/root/AmericanEagleDollar/src/CryptoNoteCore/Currency.h:76:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
       if (height >= CryptoNote::parameters::DUST_THRESHOLD_V2_HEIGHT)

**Comment by zpalmtree** [comment]
Firstly, this is the wrong repo, considering it appears you are building the core code, not the GUI wallet.
Secondly, that warning doesn't matter, you can safely ignore it.
If you are hanging whilst compiling, you probably need more RAM. Or just be patient and it will probably complete.

**Comment by hmc36093** [comment]
I get these  messages when i start  make.   I could use some help please.

root@AEDD-S1:~/AmericanEagleDollar/build# make --always-make
fatal: No annotated tags can describe 'aa0314217efc4c66481f0cf8b6caa21f6ddfb49b'.
However, there were unannotated tags: try --tags.
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.
[  0%] Built target version
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/igd_desc_parse.c.o
[  1%] Building C object external/miniupnpc/CMakeFiles/upnpc-static.dir/miniupnpc.c.o

**Comment by hmc36093** [comment]
t y zpalmtree.  i see now i got into the wallet one.
