### ISSUE TITLE
display sub-views (qml) inside qt creator design view

### ISSUE THREAD

**Issue by cryptoBOOOOM** [turtlecoin/turtle-wallet-go#33]
I can open nestmain.qml which renders fine, but when i want to edit settings.qml for example the designer is not rendering the file.

Somehow it cannot render the parent view.

**Comment by cryptoBOOOOM** [comment]
![trtl2](https://user-images.githubusercontent.com/3755177/43997400-776b863e-9dda-11e8-86cf-936c1ed00291.JPG)
![trtl1](https://user-images.githubusercontent.com/3755177/43997401-77b52eba-9dda-11e8-95e6-dee800b2156d.JPG)

**Comment by woodyjon** [comment]
Yes indeed, that's why I don't use creator.

**Comment by cryptoBOOOOM** [comment]
What else do you use then?

**Comment by woodyjon** [comment]
The code, without wysiwyg.
