### ISSUE TITLE
TurtleCoin-Nest binary from 0.32 release archive is old version (Linux)

### ISSUE THREAD

**Issue by rixombea** [turtlecoin/turtle-wallet-go#34]
TurtleCoin-Nest binary is still at 0.31, other bundled binaries (TurtleCoind and turtle-service) are upgraded version (0.80)

Extracted binaries from TurtleCoin-Nest-0.32-Linux.tar.gz downloaded from release page:
```
$ ./TurtleCoind --version
2018-Aug-26 11:45:02.336183 INFO    Welcome to TurtleCoin v0.8.0.1268 ()
TurtleCoin v0.8.0.1268 ()

$ ./turtle-service --version
turtle-service v0.8.0.1268 ()

$ ./TurtleCoin-Nest
time="2018-08-26T11:45:28+07:00" level=info msg="Application started" version=0.31
```

**Comment by woodyjon** [comment]
Is there mention of the node fee in the transfer section of the interface? Maybe it's just a version number issue.

**Comment by rixombea** [comment]
no, it was prompted me to download new version (0.32) on startup.

also, on the repo `versionNest` on constants.go file already updated to 0.32, so I think not version number problem

**Comment by woodyjon** [comment]
I must have mixed it up on linux. Will be able to fix that in a week.

**Comment by brandonlehmann** [comment]
We're working on fixing this in @woodyjon 's absence.
