### ISSUE TITLE
[BUG] Node fee possibly uninitialized/incorrect in some cases

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtle-wallet-go#38]
Don't have much info to go on, but a user reported seeing this with Nest, with the default node of public.turtlenode.io. - https://cdn.discordapp.com/attachments/471023390954618883/485984721667489792/01-40-07.023_image.jpg

I tested immediately after with zedwallet and saw the correct fee of 250 TRTL, so it's possibly on nest's end. My best guess would be an uninitialized variable, since the user also said something about a 15k TRTL node fee, however, upon looking at the code, I wasn't sure where that could be occurring.

**Comment by brandonlehmann** [comment]
Looks like it's handled pretty well via https://github.com/turtlecoin/turtle-wallet-go/blob/a78a0c0291fc086f92e9d6fa50eeb824eb91042d/turtlecoinwalletdrpcgo/walletdrpc.go#L285

**Comment by zpalmtree** [comment]
Yeah that's what I saw, now sure what's going on

**Comment by brandonlehmann** [comment]
Just checked `turtle-service` and it's okay

```javascript
{"jsonrpc":"2.0","result":{"address":"TRTLv1pacKFJk9QgSmzk2LJWn14JGmTKzReFLz1RgY3K9Ryn7783RDT2TretzfYdck5GMCGzXTuwKfePWQYViNs4avKpnUbrwfQ","amount":25000}}
```

**Comment by brandonlehmann** [comment]
I can't replicate this at all...

**Comment by woodyjon** [comment]
Do we know to which node this user was connected?

**Comment by rashedmyt** [comment]
I have encountered this issue 
![selection_012](https://user-images.githubusercontent.com/25506588/44988708-42cf0f00-afa9-11e8-9900-9c4b5ac6f286.png)
The node is public.turtlenode.io

**Comment by woodyjon** [comment]
@zpalmtree when my node is importing blocks, feeinfo returns this: [address: amount:1.936028526e+09], while I started Turtlecoind without specifying fees, so should be 0. As soon as importing blocks is finished and node is synced, nodefee returns the correct fee. So I'm guessing that at some syncing points, feeinfo does not return the right amount. Could you please check the implementation of it?

Besides, I implemented this, which should help a bit: https://github.com/turtlecoin/turtle-wallet-go/commit/d38098189d31f1396bb3a010d3cc3b3309e11484

**Comment by woodyjon** [comment]
I actually improved it by implementing this: https://github.com/turtlecoin/turtle-wallet-go/commit/31e6b4ab10aac2602350e346fa024701ab3bfa68
I consider that the fee info is invalid when fee is > 0 and address is nil. And I request again 15 sec later.

**Comment by zpalmtree** [comment]
@brandonlehmann Might know more, as he did the implementation of node fees.

**Comment by brandonlehmann** [comment]
Interesting. I’ll check into that.
