### ISSUE TITLE
allow for custom turtlecoind rpc ip:port

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtle-wallet-go#4]
further to #3 should be able to specify which turtlecoind is used (maybe hidden in a menu) ip:port

**Comment by woodyjon** [comment]
Yes, I'm definitely adding this. I work incrementally and wanted to implement remote nodes quickly and easily, without too much work on the UI. I'll now add a settings menu for those things.

**Comment by SoreGums** [comment]
nice one :)

**Comment by woodyjon** [comment]
implemented in 0.20
