### ISSUE TITLE
Option to support loading checkpoints

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-go#41]
We get a lot of users that really wish they could use/load the checkpoints with Nest. Is this something that can be added?

**Comment by woodyjon** [comment]
implemented here: 9000c753594b9908f960dc12b9e406f6ea4400ac

**Comment by woodyjon** [comment]
To make it easy for the user, my idea is to include the latest checkpoints.csv in the bundle. There is no choosing file or location or anything. If he wants a more recent one, he just has to replace the checkpoints.csv in the app folder.

**Comment by brandonlehmann** [comment]
Awesome. I'll take it. :)
