### ISSUE TITLE
QQmlApplicationEngine failed to load component

### ISSUE THREAD

**Issue by cchris-org** [turtlecoin/turtle-wallet-go#46]
Hi!

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
DISTRIB_CODENAME=tara
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"

`>TurtleCoin-Nest-0.35$ ./TurtleCoin-Nest.sh`
`
time="2018-10-26T09:00:50+02:00" level=info msg="Application started" version=0.35
QQmlApplicationEngine failed to load component
qrc:/qml/nestmain.qml:13 Type ApplicationWindow unavailable
file:///Downloads/TurtleCoin-Nest-0.35/qml/QtQuick/Controls.2/Material/qmldir:-1 plugin cannot be loaded for module ".Downloads.TurtleCoin-Nest-0.35.qml.QtQuick.Controls.Material": Module namespace 'QtQuick.Controls.Material' does not match import URI '.Downloads.TurtleCoin-Nest-0.35.qml.QtQuick.Controls.Material'
`

Any Idea?

**Comment by woodyjon** [comment]
Hello!

Could you please make sure your extract was successful? Those kinds of issues sometimes happen with bad extracts or extracts to wrong locations.

**Comment by cchris-org** [comment]
hi!
extracted location is my home path(***), so it can not be sooo wrong :)
and, as you can see, downloaded and extracted without errors.

> download and verify checksum
`***$:~ sha256sum TurtleCoin-Nest-0.36-Linux.tar.gz`
`***$:~ a9f9ea43a195683b2dcdb85437fb1aa0175fc793ceb05cf0e101dad4d5ba6f11  TurtleCoin-Nest-0.36-Linux.tar.gz`

> extract and ..
`***$:~ tar -xf TurtleCoin-Nest-0.36-Linux.tar.gz `
`***$:~ cd TurtleCoin-Nest-0.36/`
`***$:~ ./TurtleCoin-Nest.sh`
`***$:~ time="2019-01-02T07:31:52+01:00" level=info msg="Application started" version=0.36
QQmlApplicationEngine failed to load component
qrc:/qml/nestmain.qml:38 Type ScrollBar unavailable
file:///home/***/Downloads/TurtleCoin-Nest-0.36/qml/QtQuick/Controls.2/Material/qmldir:-1 plugin cannot be loaded for module ".home.***.Downloads.TurtleCoin-Nest-0.36.qml.QtQuick.Controls.Material": Module namespace 'QtQuick.Controls.Material' does not match import URI '.home.***.Downloads.TurtleCoin-Nest-0.36.qml.QtQuick.Controls.Material'`

> verifying if qmldir exist ..
`***$:~ ls -l /home/***/Downloads/TurtleCoin-Nest-0.36/qml/QtQuick/Controls.2/Material/qmldir`
> and it exists!
`***$:~ -rw-r--r-- 1 *** *** 151 Okt 29 17:57 /home/***/Downloads/TurtleCoin-Nest-0.36/qml/QtQuick/Controls.2/Material/qmldir`

**Comment by LithyRiolu** [comment]
Are you able to re-simulate this issue again for us please?

I myself use Linux Mint but cinnamon and not tara

**Comment by LithyRiolu** [comment]
Closing because there is no response and I’m also using Linux Mint and everything works as it should. 

I will open this again if needed.
