### ISSUE TITLE
Wallet GUI size glitch

### ISSUE THREAD

**Issue by TurtleForGaming** [turtlecoin/turtle-wallet-go#47]
### Information
**Operating System**: Windows 10
**Version:** 0.36
**Binary Source:** pre-compiled

#### Expected Behavior
The wallet gui should resize properly when going on 2nd screen

#### Current Behavior
When passing the the wallet to the second screen it resize it but it's hiding the lower / right part of the wallet and when trying to resize it replaces with white border: http://i64.tinypic.com/2zxxdtk.png

**Comment by woodyjon** [comment]
I guess your 2nd screen must have a low resolution. If it has a smaller resolution than the nest window, it cannot display everything. In that case, you can scroll in the window with your scroll wheel or by dragging the background.

**Comment by TurtleForGaming** [comment]
Is it has a lower resolution but when I resize it blanks the windows see the video (https://www.youtube.com/watch?v=lb26KKgnsk0)

**Comment by woodyjon** [comment]
I see, thanks. Sorry but I am not sure where does that come from. On a high enough resolution screen, I do not have any issues resizing.

**Comment by LithyRiolu** [comment]
Are you able to re-simulate this issue again for us please?

**Comment by LithyRiolu** [comment]
I'm going to close this issue and there are 2 reasons why;

1) Nobody has reported back nor reported this issue twice.

2) In the future release of **v0.38**, I have limited the window size in attempt to fix this issue plus the components aren't dynamically set out so changing the size of the window essentially done nothing, *you can still make it smaller, you can't scale it bigger than it's default*.
