### ISSUE TITLE
doesn't appear like app is able to recover being interupted

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtle-wallet-go#5]
1. opened TurtleCoin-Nest on windows10 x64
2. started a wallet import via remote daemon using keys
3. went home (laptop to sleep)
4. opened up laptop the next day (16hrs later)
5. TurtleCoin-Nest didn't keep syncing the wallet, just sat there at 118,000/364,000
6. closed TurtleCoin-Nest
7. opened TurtleCoin-Nest again.
8. Couldn't see a way to remsume, had to start again.
9. deleted TurtleCoin-Nest-0.15 folder - will checkout the next release :D

so at 5. above app needs to do something to verify things are working, instead of waiting for the next thing to happen :)

**Comment by woodyjon** [comment]
point 8, when you say could not see a way to resume, you could just open the created wallet, no? It should be in the folder. (you know, the folder you deleted ;-))

**Comment by woodyjon** [comment]
On my machine (also win 10 x64), it resumes fine after a sleep.

**Comment by woodyjon** [comment]
Did you still experience the problem?

**Comment by SoreGums** [comment]
you know I looked in %appdata% for the wallet. 
found it later in the program folder.

any reason why need files in %appdata%? or was i seeing another wallets folder there, i don't remember.

downloading latest now to give it a whirl

**Comment by SoreGums** [comment]
all good, 0.20, went to sleep while connected to a remote (localhost) node. 
woke up and sync continued 🥁

**Comment by SoreGums** [comment]
looks like it is a qml/qt thing that uses %appdata% not your app directly

![image](https://user-images.githubusercontent.com/317/39080355-812c77aa-4556-11e8-93de-0a47b6bc9d0e.png)

because this folder was in %appdata% i assumed the app put files in %appdata% and didn't bother looking in the program folder ;)

**Comment by woodyjon** [comment]
Ha ok I see!
