### ISSUE TITLE
Error communicating with turtle-services via rpc

### ISSUE THREAD

**Issue by TurtlesiHill** [turtlecoin/turtle-wallet-go#51]
Hi, 

I am trying to import from a paper wallet using spend and view keys.

![screenshot 2019-01-01 at 22 16 32](https://user-images.githubusercontent.com/43421684/50577687-aa00b100-0e2d-11e9-8fde-ac0208124ab2.png)
![screenshot 2019-01-02 at 00 13 04](https://user-images.githubusercontent.com/43421684/50577688-aa00b100-0e2d-11e9-9029-18c44bab9e58.png)
<img width="300" alt="screenshot 2019-01-02 at 00 51 04" src="https://user-images.githubusercontent.com/43421684/50577689-aa00b100-0e2d-11e9-9aed-d730110e38d5.png">

Mac OS, had v0.35, and now installed and several times reinstalled and rebooted a 0.36 and keep getting the same message "Error opening wallet. error communicating with turtle-services via rpc"

The issue is not turtle-services running in the background as I checked in Activity monitor.
Seems like the issue may be is it is now running in a first place as Rock pointed out.

Tried to disable all Avas Shields I have as well as whitelist the app file where I could.
Cleared all caches etc, rebooted again. The issue remains.

Tried to uninstall 36 and install back 35 and the issue is now here too. 

darkmatter23 advised to just take the .wallet file it creates anyway and then try to just Open it but same message. Can't open any wallet of mine on Nest now.

Any ideas, please?

**Comment by TurtlesiHill** [comment]
Thanks Jon, really appreciate it since your Nest wallet is simply my favourite.

**Comment by woodyjon** [comment]
So is it correct that it is not only about importing the paper wallet, but actually you can not launch anything in nest?
It seems it does not find turtle-service in the app bundle. Or maybe you already have turtle-service running?

**Comment by TurtlesiHill** [comment]
Yes, originally I was just trying to import the paper wallet. Didn't work - first screenshot.
Then I tried to open my main wallet and that all of a sudden stopped working as well.
So I deleted the 0.36 completely and tried to sign in on newly installed 0.35 - doesn't now work neither.
There's virtually no way for me to open any account using Nest wallet. 
TRTL services not running in Activity monitor.

**Comment by woodyjon** [comment]
May I ask your version of macos?

**Comment by rkp889** [comment]
fyi, i also have this occurring on a win 10 build 1803, Nest v0.36

**Comment by TurtlesiHill** [comment]
Woody, my current version of MacOS is Mohave 10.12.2.
I've updated in the middle of the problems to see if it would helped but no luck :/

**Comment by SoreGums** [comment]
issues is the params

https://github.com/turtlecoin/turtle-wallet-go/blob/ffc8b601d1f922a9e850194262d153738eb8e0c8/walletdmanager/walletdmanager.go#L369

--log-file now

**Comment by brandonlehmann** [comment]
Error resolved in https://github.com/turtlecoin/turtle-wallet-go/commit/a495b51658e4e40e41ab01c7cade20a7d777b79a
