### ISSUE TITLE
Error in copying seed

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-go#53]
Moved from https://github.com/turtlecoin/turtlecoin/issues/682

![50840026-8ba23480-139c-11e9-893b-35e534615ba1](https://user-images.githubusercontent.com/20562132/50840732-2f55fb00-1331-11e9-89af-39e83684e7b5.png)

1.latest TurtleCoin-Nest-0.36-Mac.zip
2.In the page showing your seed after registration, click OK and nothing happen just stay there
3.MAC OS Sierra 10.12.6 (16G1618)

@hehanbo1990

**Comment by LithyRiolu** [comment]
I had this issue using Linux and found out that the GoLang copy & paste element is from https://github.com/atotto/clipboard. Even though it say's it has OSX support and warns Linux users to install `xclip` or `xsel` in order for this to work. I have just installed `xclip` and retested the **Copy to clipboard** button and it now works now. 

Can I suggest you, or another mac user, to install `xclip` and test this feature again please? I have found a link for Mac instructions https://brewinstall.org/Install-xclip-on-Mac-with-Brew/ *(lets hope it works for yous)*

**Comment by LithyRiolu** [comment]
I set a bounty for an OSX user to help replicate this issue.

The user was able to paste the wallet information before xclip was installed. I can only guess that https://github.com/atotto/clipboard may have been updated or it was a one off bug. 

If however this does happen again with OSX users (and a future note to Linux users), then please go ahead and install xclip.

**Comment by Sajo8** [comment]
Is there anyway to copy to the clipboard without requiring xclip? Many people don't have it and it'd be pain to install it separately (even if it's a single command in the terminal)

**Comment by brandonlehmann** [comment]
> Is there anyway to copy to the clipboard without requiring xclip? Many people don't have it and it'd be pain to install it separately (even if it's a single command in the terminal)

See above.

**The user was able to paste the wallet information before xclip was installed.**
