### ISSUE TITLE
Previous Transfers Not Displaying Correctly

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtle-wallet-go#56]
Previous balances are not displaying correctly in the latest release on any platform that I can see.

**Comment by mrchenmo** [comment]
I also encountered the same problem, you guys can  fix it?

**Comment by mrchenmo** [comment]
Windows version of the client  0.37

**Comment by brandonlehmann** [comment]
Someone will surely fix it

**Comment by BigslimVdub** [comment]
<img width="1041" alt="nest 37" src="https://user-images.githubusercontent.com/30030687/52029579-673c0280-24d9-11e9-9dea-99ea7a4fb0dd.png">
yes
osx 10.13.6 binary

**Comment by Nash-Cash** [comment]
the same for me on mac.. i will look windows and linux later. In Discord they told, its a bug on all os

**Comment by odedgoro** [comment]
Same Here Windows 10 64 Bit Client 0.37

**Comment by LithyRiolu** [comment]
Fixed
