### ISSUE TITLE
Wallet address clipping with copy button

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtle-wallet-go#9]
See pic :)

This is on linux.
![turtlecoin nest_003](https://user-images.githubusercontent.com/22151537/38969929-94cc58e8-438a-11e8-9de5-c9e0232c0d17.png)

**Comment by woodyjon** [comment]
found the bug: too many W's in your address! I'll check how to limit the number of M's and Ws.

More seriously, thanks, I will fix this. I knew I'd have to one day ;-)

**Comment by woodyjon** [comment]
Fixed in the next release. I moved the copy button below the address, as it is difficult to have a text field which is both selectable and autoresizing.
